name: bug2
# packages in environment at /Users/nicholas/miniconda3/envs/bug:
#
abyss                     1.9.0               boost1.61_4    bioconda
aragorn                   1.2.38                        1    bioconda
arrow                     0.10.0                    <pip>
barrnap                   0.8                           0    bioconda
biopython                 1.68                      <pip>
blast                     2.7.1               boost1.64_1    bioconda
boost                     1.64.0                   py36_4    conda-forge
boost-cpp                 1.64.0                        1    conda-forge
bwa                       0.7.17               pl5.22.0_0    bioconda
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
curl                      7.54.1                        0    conda-forge
expat                     2.2.1                         0    conda-forge
fastqc                    0.11.5               pl5.22.0_3    bioconda
fontconfig                2.12.1                        5    conda-forge
freetype                  2.7                           1    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                         0    conda-forge
gmp                       6.1.2                         0    conda-forge
gnutls                    3.5.15                        0    conda-forge
graphviz                  2.38.0                        5    conda-forge
hmmer                     3.1b2                         3    bioconda
icu                       58.1                          1    conda-forge
infernal                  1.1.2                         0    bioconda
jpeg                      9b                            2    conda-forge
krb5                      1.14.2                        0    conda-forge
libdb                     6.1.26                        0    bioconda
libgcc                    4.8.5                         1
libgd                     2.2.5                         0    conda-forge
libiconv                  1.14                          4    conda-forge
libidn                    7.45.0                        1    bioconda
libidn11                  1.33                          0    conda-forge
libpng                    1.6.28                        1    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.7                         0    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxml2                   2.9.5                         0    conda-forge
libxslt                   1.1.29                        5    conda-forge
make                      4.2.1                         0    conda-forge
minced                    0.2.0                         1    bioconda
mkl                       2017.0.3                      0
mummer                    3.23                          4    bioconda
ncurses                   5.9                          10    conda-forge
nettle                    3.3                           0    conda-forge
numpy                     1.13.1                   py36_0
openjdk                   8.0.121                       1
openssl                   1.0.2l                        0    conda-forge
parallel                  20170422             pl5.22.0_0    bioconda
pcre                      8.39                          0    conda-forge
perl                      5.22.0.1                      0    conda-forge
perl-aceperl              1.92                          0    bioconda
perl-algorithm-munkres    0.08                          0    bioconda
perl-appconfig            1.71                          0    bioconda
perl-array-compare        2.11                          0    bioconda
perl-bio-asn1-entrezgene  1.72                          1    bioconda
perl-bio-featureio        1.6.905                       0    bioconda
perl-bio-phylo            0.58                          0    bioconda
perl-bio-samtools         1.43                          0    bioconda
perl-bioperl              1.6.924              pl5.22.0_7    bioconda
perl-bioperl-core         1.6.924              pl5.22.0_2    bioconda
perl-bioperl-run          1.006900                      2    bioconda
perl-cgi                  4.22                          3    bioconda
perl-class-inspector      1.28                          0    bioconda
perl-class-method-modifiers 2.11                          1    bioconda
perl-clone                0.38                          0    bioconda
perl-common-sense         3.74                          0    bioconda
perl-convert-binary-c     0.78                          0    bioconda
perl-convert-binhex       1.125                         0    bioconda
perl-crypt-rc4            2.02                          0    bioconda
perl-data-stag            0.14                          0    bioconda
perl-db-file              1.835                         5    bioconda
perl-dbd-sqlite           1.50                          1    bioconda
perl-dbi                  1.636                         0    bioconda
perl-devel-globaldestruction 0.13                          1    bioconda
perl-digest-hmac          1.03                 pl5.22.0_1    bioconda
perl-digest-perl-md5      1.9                           0    bioconda
perl-email-date-format    1.005                         0    bioconda
perl-encode-locale        1.05                 pl5.22.0_4    bioconda
perl-error                0.17024                       0    bioconda
perl-exporter-tiny        0.042                         1    bioconda
perl-file-listing         6.04                          0    bioconda
perl-file-slurp-tiny      0.004                         0    bioconda
perl-file-sort            1.01                 pl5.22.0_1    bioconda
perl-file-which           1.20                          0    bioconda
perl-font-afm             1.20                          0    bioconda
perl-gd                   2.56                          3    bioconda
perl-graph                0.9704                        0    bioconda
perl-graphviz             2.20                          1    bioconda
perl-html-element-extended 1.18                          0    bioconda
perl-html-entities-numbered 0.04                          0    bioconda
perl-html-formatter       2.14                          0    bioconda
perl-html-parser          3.72                 pl5.22.0_1    bioconda
perl-html-tableextract    2.13                          0    bioconda
perl-html-tagset          3.20                 pl5.22.0_1    bioconda
perl-html-tidy            1.56                          1    bioconda
perl-html-tree            5.03                          0    bioconda
perl-html-treebuilder-xpath 0.14                          0    bioconda
perl-http-cookies         6.01                          0    bioconda
perl-http-daemon          6.01                          0    bioconda
perl-http-date            6.02                 pl5.22.0_1    bioconda
perl-http-message         6.11                          0    bioconda
perl-http-negotiate       6.01                          0    bioconda
perl-image-info           1.38                          0    bioconda
perl-image-size           3.300                         0    bioconda
perl-io-html              1.001                pl5.22.0_1    bioconda
perl-io-sessiondata       1.03                          0    bioconda
perl-io-socket-ssl        2.024                         0    bioconda
perl-io-string            1.08                 pl5.22.0_1    bioconda
perl-io-stringy           2.111                         0    bioconda
perl-io-tty               1.12                          0    bioconda
perl-ipc-run              0.94                          0    bioconda
perl-jcode                2.07                          0    bioconda
perl-json                 2.90                          1    bioconda
perl-json-xs              2.34                          0    bioconda
perl-libwww-perl          6.15                          0    bioconda
perl-libxml-perl          0.08                          0    bioconda
perl-list-moreutils       0.413                         1    bioconda
perl-lwp-mediatypes       6.02                 pl5.22.0_1    bioconda
perl-lwp-protocol-https   6.06                          2    bioconda
perl-mailtools            2.14                          0    bioconda
perl-math-cdf             0.1                           3    bioconda
perl-math-derivative      0.04                          0    bioconda
perl-math-random          0.72                          0    bioconda
perl-math-spline          0.02                          0    bioconda
perl-mime-lite            3.030                         0    bioconda
perl-mime-tools           5.507                         0    bioconda
perl-mime-types           2.12                          0    bioconda
perl-mldbm                2.05                          0    bioconda
perl-module-runtime       0.014                         1    bioconda
perl-moo                  2.001000                      1    bioconda
perl-mozilla-ca           20160104                      0    bioconda
perl-net-http             6.09                          0    bioconda
perl-net-ssleay           1.74                          0    bioconda
perl-ntlm                 1.09                          1    bioconda
perl-ole-storage_lite     0.19                          0    bioconda
perl-parse-recdescent     1.967013                      0    bioconda
perl-pdf-api2             2.025                         2    bioconda
perl-postscript           0.06                          0    bioconda
perl-role-tiny            2.000001                      1    bioconda
perl-set-scalar           1.29                          0    bioconda
perl-soap-lite            1.19                          0    bioconda
perl-sort-naturally       1.03                          0    bioconda
perl-spreadsheet-parseexcel 0.65                          0    bioconda
perl-spreadsheet-writeexcel 2.40                          0    bioconda
perl-statistics-descriptive 3.0612                        0    bioconda
perl-sub-exporter-progressive 0.001011                      1    bioconda
perl-svg                  2.64                          0    bioconda
perl-svg-graph            0.02                          0    bioconda
perl-task-weaken          1.04                          0    bioconda
perl-template-toolkit     2.26                          0    bioconda
perl-test-leaktrace       0.15                          0    bioconda
perl-test-pod             1.51                          0    bioconda
perl-threaded             5.22.0              pl5.22.0_12    bioconda
perl-tie-ixhash           1.23                 pl5.22.0_1    bioconda
perl-timedate             2.30                          0    bioconda
perl-tree-dag_node        1.29                          0    bioconda
perl-type-tiny            1.000005                      0    bioconda
perl-unicode-map          0.112                         0    bioconda
perl-uri                  1.71                          0    bioconda
perl-www-robotrules       6.02                          0    bioconda
perl-xml-dom              1.45                          0    bioconda
perl-xml-dom-xpath        0.14                          0    bioconda
perl-xml-filter-buffertext 1.01                          0    bioconda
perl-xml-libxml           2.0124                        0    bioconda
perl-xml-libxslt          1.94                          0    bioconda
perl-xml-namespacesupport 1.11                          0    bioconda
perl-xml-parser           2.44                          4    bioconda
perl-xml-regexp           0.04                          0    bioconda
perl-xml-sax              0.99                          0    bioconda
perl-xml-sax-base         1.08                          0    bioconda
perl-xml-sax-expat        0.51                          0    bioconda
perl-xml-sax-writer       0.56                          0    bioconda
perl-xml-simple           2.22                          0    bioconda
perl-xml-twig             3.49                          0    bioconda
perl-xml-writer           0.625                         0    bioconda
perl-xml-xpath            1.33                          0    bioconda
perl-xml-xpathengine      0.14                          0    bioconda
perl-yaml                 1.18                          0    bioconda
picard                    2.14.1                   py36_0    bioconda
pip                       9.0.1                    py36_0    conda-forge
prodigal                  2.6.3                         0    bioconda
prokka                    1.12                          3    bioconda
python                    3.6.3                         0    conda-forge
PyYAML                    3.12                      <pip>
readline                  6.2                           0    conda-forge
samtools                  1.6                           0    bioconda
scaffoldsis               0.0.4                     <pip>
seqtk                     1.2                           0    bioconda
setuptools                36.6.0                   py36_1    conda-forge
sickle-trim               1.33                          1    bioconda
six                       1.11.0                    <pip>
spades                    3.11.1                   py36_0    bioconda
sqlite                    3.13.0                        1    conda-forge
tbl2asn                   25.3                          0    bioconda
tidyp                     1.04                          0    bioconda
tk                        8.5.19                        2    conda-forge
wheel                     0.30.0                     py_1    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
