#  the structure is {program_category:[[executable, name, version_command, version_line, pattern],
#                                      [another_executable, its_name, version_line]}
all_programs_dict = {
    "mandatory_programs": [
        ['seqtk', 'seqtk'],
         # "", "stderr",
         # 2, r"^Version: (?P<version>[^']+)$"],
        ['samtools','samtools'],
         # "--version", "stdout",
         # 0, r"^Version: (?P<version>[^\s']+).*$"],
        ['picard', 'Picard'],
         # "CollectInsertSizeMetrics --version", "stderr",
         # 0, r"^(?P<version>[^\s']+).*$"],
        ['blastn', "BLASTn"],
         # "-version", "stdout", 0, r"^ Package: blast (?P<version>[^\s']+).*$"],
        ['makeblastdb', "makeblastdb"],
        ["nucmer", "nucmer"],
        ["mummer", "MUMmer"],
        ["mummerplot", "MUMmerplot"],
        ["delta-filter", "delta-filter"],
        ["show-coords", "show_coords"],
        ['R', "R"],
        ['cgview', 'cgview'],
        ['cgview_xml_builder.pl', 'cgview_xml_builder'],
        ['bwa', 'BWA'],
        ["perl", "perl"],
    ],
    "opt_programs": [
        ["prokka", "PROKKA"],
        ['fastqc', 'FastQC'],
        ['sickle', 'sickle-trim'],
        ['mauve','mauve'],
        ['ribo', 'riboSeed'],
        ['skesa', 'skesa'],
        ['FGAP', 'fgap'],
        ['minimus', 'minimus'],
        ['sam2afg','sam2afg'],
        ['aragorn', 'aragorn'],
        ['prodigal','prodigal'],
        ['hmmer3', 'hmmer3'],
        ["python2", "python2"], # needed for ragout
        ['ragout.py', 'ragout'],
        ['infernal','infernal'],
        ['bank-transact','bank-transact'],
        ['rnammer','rnammer'],
        ['tbl2asn','tbl2asn'],
        ['celera','celera'],
        ["abyss-pe","abyss"],
        ["abyss-sealer","abyss-sealer"],
        ['gapfiller','gapfiller'],
        ['sspace','sspace'],
        ['asn2gb','asn2gb'],
        ['amos','amos'] ,
        ['masurca','masurca'],
        ['gfinisher', 'gfinisher'],
        ['pilon','pilon'],
        ['vcffilter','vcffilter'],
        ['vcffixup', 'vcffixup'],
        ['cgview','cgview'],
        ['spades.py','spades'],
        ['sis.py','sis'],
        ['multifasta.py','multifasta'],
        ['barrnap','barrnap'],
    ],
}
